### ISSUE TITLE
maybe provide a link to paper itself in this repo

### ISSUE THREAD

**Issue by epogrebnyak** [tyleransom/AES-Roy-Majors#1]
For example this link: https://www.iza.org/publications/dp/13370/selective-migration-occupational-choice-and-the-wage-returns-to-college-majors

**Comment by tyleransom** [comment]
Thanks for the suggestion! I hadn’t thought to do that since usually people
read the paper and then go to the code. I’ll be sure to fix this once the
paper comes out in print (it’s in final copyediting right now).
